### ISSUE TITLE
np.fromfile reads wrong data when the start index s is too close to 0

### ISSUE THREAD

**Issue by KinWaiCheuk** [jthickstun/pytorch_musicnet#6]
I will use 1819.npy to demonstrate this issue.
I tried to load this numpy array by using `np.fromfile` just like what you did in the `MusicNet` class `access` function.
```

s = 10
sz_float = 4
scale = 1
window = 16384

with open('../../pytorch_musicnet/data/test_data/1819.npy', 'rb') as f:
    f.seek(s*sz_float, os.SEEK_SET)
    x = np.fromfile(f, dtype=np.float32, count=int(scale*window))

plt.plot(x)
plt.ylim(-0.01,0.01)
```
Whenever the position index `s` is too close to 0, a spike will appear in the array `x`
See the picture below for the spike appear at the beginning of the audio data
![debug](https://user-images.githubusercontent.com/37035802/60442672-1a0cba00-9c4c-11e9-9109-400133c02873.png)

I have a feeling that this might affect the training, since the value for that spike is huge, the weight of the neural network might update wrongly if such a array is generated.

I propose the following fix

```
        else:
            fid,_ = self.records[rec_id]
#             with open(fid, 'rb') as f:
#                 f.seek(s*sz_float, os.SEEK_SET)
#                 x = np.fromfile(f, dtype=np.float32, count=int(scale*self.window))
            x = np.load(fid)
            x = x[s:s+self.window]
```
However, the dataloading speed is super slow when replacing `np.fromfile` with `np.load`

Do you have a better idea on how to fix it?

**Comment by jthickstun** [comment]
Yes. Take a look at commit 944961706908e5ea6139485ce23f2a7c7f183d8d. The latest repo with that commit will cache binary files without the numpy headers and should fix this issue at the front of the file.

Your proposed solution is correct but (as you noticed) it is super slow because it reads the whole file into memory when you really just want the small chunk associated with an individual data point.
